// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
/* eslint-disable */
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The env() helper guarantees a string and throws an error if it is missing
    url: env("DATABASE_URL"), 
  },
});
